name: CI

on:
  push:
    paths-ignore:
      - 'docker-compose.yml'
      - '**.md'
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Whether to deploy DockerHub and GHCR'
        required: true
        default: '0'

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Taipei

    steps:
      # prepare
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set environment variables
        run: |
          echo "BUILD_TAG=$(date +%Y%m%d)" >> $GITHUB_ENV

      # login
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # cache
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.BUILD_TAG }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ env.BUILD_TAG }}-buildx-

      # build & push
      - name: Build image and Push to Container Registries
        uses: docker/build-push-action@v3
        if: ${{ github.event_name == 'push' || github.event.inputs.deploy == '1' }}
        with:
          context: .
          tags: |
            ${{ github.repository }}:${{ env.BUILD_TAG }}
            ghcr.io/${{ github.repository }}:${{ env.BUILD_TAG }}
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
